FROM image-builder-base

#http://wiki.lemaker.org/BananaPro/Pi:Building_u-boot,_script.bin_and_linux-kernel

WORKDIR /workspace

#Get the BoardSupportPackage repository:
RUN git clone --depth 1 https://github.com/LeMaker/lemaker-bsp.git lemaker/

#change kernel config
#CMD ["make linux-config"]

#If for Banana Pro:
#CMD ["./configure BananaPro && make","bash"]

#If for Banana Pi:
#CMD ["./configure BananaPi && make","bash"]

CMD ["./builder/build.sh"]
